### PR TITLE
pullapprove: remove it

### PR DESCRIPTION
**Pull request by grahamwhaley**
We are moving away from pullapprove. Remove its config file.

Fixes: #72

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by jodh-intel** [comment]
@grahamwhaley - github is saying your branch is out of date...?

**Comment by jodh-intel** [comment]
Merging...

**Comment by jodh-intel** [comment]
Webhook deleted.

**Pull request merged**
