### PR TITLE
docs: Specify Architecture Committee & Working Committee members as list

### LINKED ISSUE #18: Specify Architecture & Working Committee members in a list
For clarity, list all members of the Architecture Committee and the Working Committee as a list, with appropriate links.

### PR DESCRIPTION
**Pull request by jodh-intel**
For clarity, list all members of the Architecture Committee as a list,
with appropriate links.

Also created a separate subsection to allow for a quick jump to current
members.

Fixes #18.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by jodh-intel** [comment]
Branch updated to also reformat the current list of Working Comittee members.

**Comment by grahamwhaley** [comment]
Just as a /cc heads up, as you are all named in this doc change.
@jessfraz
@sameo
@tallclair
@gnawux
@WeiZhang555
@amyleeland
@jmknyc06

**Comment by grahamwhaley** [comment]
Nine days and no complaints - so I'll merge it then...

**Comment by jodh-intel** [comment]
*"Silence is Compliance"* - That idea could take off!

**Pull request merged**
