### PR TITLE
Update Results.md

### LINKED ISSUE #227: Elections September 2021
Election officials approved by AC: September 7
Candidacy open: September 8-16
"Debate period": September 17-27
Voting: September 28 - October 3
Results: October 4

### LINKED ISSUE #266: Could we move the Kata Containers Architecture Committee meeting to one hour earlier?
Currently the Kata Containers A/C meeting has been happening at 3PM UTC.
However, we've noticed some conflicts for members of the Kata Containers' Architecture Committee.

With this in mind, could we consider holding the meeting at 2PM UTC, at least while the DST doesn't hit us again?

### PR DESCRIPTION
**Pull request by wainersm**
Update the results document for the September 2021 Kata Containers Architecture Committee elections.

Fixes #227

Signed-off-by: Wainer dos Santos Moschetta \<wainersm@redhat.com\>

### CODE REVIEW

**Review by raravena80 — APPROVED** [review]

**Comment by wainersm** [comment]
@fidencio @egernst @amshinde , hi all, mind to review and approve too?

**Review by fidencio — APPROVED** [review]
thanks @wainersm & @raravena80 for taking care of this election!

**Comment by fidencio** [comment]
@wainersm,
```
Fixes #266
```

Shouldn't it be #227?  Or are you planning to create a new issue?

**Comment by wainersm** [comment]
> @wainersm,
> 
> ```
> Fixes #266
> ```
> 
> Shouldn't it be #227? Or are you planning to create a new issue?

I memorized the wrong number :)
Let me fix it.

**Pull request merged**
