### PR TITLE
readme: update AC following 2024 H1 elections

### PR DESCRIPTION
**Pull request by sprt**
Removes Fabiano and Samuel, and adds Anastassios and Zvonko.

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @sprt

**Review by ildikov — APPROVED** [review]
Thank you for doing the update!

**Comment by stevenhorsman** [comment]
@sprt - I'm not sure if you've recently changed you GitHub display name, but the DCO is erroring with:
```
Expected "Aurélien <abombo@microsoft.com>", but got "Aurélien Bombo <abombo@microsoft.com>"
```

**Comment by sprt** [comment]
Ah this is because I created the PR using the GH UI and GH populated the git author field with my GH display name (Aurelien) instead of my full name. Fixed!

**Comment by bergwolf** [comment]
Could you also update `elections/arch-committee-2024-04/Results.md`?

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @sprt !

**Comment by sprt** [comment]
> Could you also update `elections/arch-committee-2024-04/Results.md`?

Done

**Review by stevenhorsman — APPROVED** [review]
Thanks @sprt!

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @sprt !

**Pull request merged**
