### PR TITLE
Add getting started info

### PR DESCRIPTION
**Pull request by jodh-intel**
Add a TOC and links to installation documents for Clear Containers and runV.

### CODE REVIEW

**Comment by jodh-intel** [comment]
fyi @jimmytipit.

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
Let's not merge that one until someone from Hyper reviews it.

**Comment by jodh-intel** [comment]
@sameo - agreed.

**Comment by gnawux** [comment]
LGTM

**Pull request merged**
