### PR TITLE
elections: Remove my candidacy

### PR DESCRIPTION
**Pull request by c3d**
As indicated, my candidacy was conditional to Archana not having submitted
hers. Having seen an announce on the mailing list, I assume she will also commit
it in this repository.

Fixes: #234

Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>

### CODE REVIEW

**Comment by wainersm** [comment]
@c3d missing the <> enclosing the email address in your commit signed-off-by :D

**Comment by c3d** [comment]
> @c3d missing the <> enclosing the email address in your commit signed-off-by :D

No, actually it's that I committed from a directory where the author is set as "christophe@dinechin.org", so email and SoB don't match. Fixed.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @c3d!

**Comment by wainersm** [comment]
I think I should wait https://github.com/kata-containers/community/pull/236 before getting this merged.

**Comment by fidencio** [comment]
> I think I should wait #236 before getting this merged.

More than that, I'd like to get a review on this one from all the other runners (hey @amshinde and @egernst), and also from @wainersm and @raravena80 before having it merged.

**Comment by wainersm** [comment]
> > I think I should wait #236 before getting this merged.
> 
> More than that, I'd like to get a review on this one from all the other runners (hey @amshinde and @egernst), and also from @wainersm and @raravena80 before having it merged.

I talked with @raravena80 offline and we are ok to merge this and #236 (already merged actually) even after the nomination period (as the candidacy emails were sent on mailing list before the deadline).

**Review by wainersm — APPROVED** [review]

**Pull request merged**
