### PR TITLE
elections: Add Samuel Ortiz candidacy

### PR DESCRIPTION
**Pull request by sameo**
I'd like to renew my seat at the AC committee.

Fixes: #79

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Here is a fun fact then - It would seem @mimeriza is not a member of that kata github org, and hence his acks don't count...
@kata-containers/architecture-committee - could we get a couple of acks here to add @mimeriza to the org, and we'll fire him an invite.

**Comment by gnawux** [comment]
should we add him as an owner of the project for approving PRs in this repo?

**Comment by sameo** [comment]
@grahamwhaley I sent an invite to @mimeriza

**Comment by mimeriza** [comment]
Done

**Pull request merged**
